In [5]:
import pandas as pd
import numpy as np

In [6]:
# A numpy array
arr = np.random.randn(4) # random values from std normal distribution
print(type(arr))
print(arr, "\n")

# A pandas series made from the previous array
s = pd.Series(arr)
print(type(s))
print(s)

<class 'numpy.ndarray'>
[ 0.37354574  0.64966114  0.46204201 -0.05201144]

<class 'pandas.core.series.Series'>
0    0.373546
1    0.649661
2    0.462042
3   -0.052011
dtype: float64

In [7]:
# Creating a Pandas Series 
# s = pd.Series(data, index=index)

In [8]:
# Series from a Numpy array
pd.Series(np.arange(3), index=[2023, 2024, 2025])

2023    0
2024    1
2025    2
dtype: int64

In [9]:
# Construct a dictionary 
d = {"key_0": 2, "key_1": "3", "key_2": 5}

# Initialize series using a dictionary
pd.Series(d)

key_0    2
key_1    3
key_2    5
dtype: object

In [10]:
pd.Series(3.0, index = ["A", "B", "C"])

A    3.0
B    3.0
C    3.0
dtype: float64

In [11]:
# Define a series 
s = pd.Series([98, 73, 65], index = ['Andrea', 'Beth', 'Carolina'])

# Divide each element in the series by 10
print(s/10, '\n')

# Take the exponential of each element in the series 
print(np.exp(s), '\n')

# Original series is unchanged 
print(s)

Andrea      9.8
Beth        7.3
Carolina    6.5
dtype: float64

Andrea      3.637971e+42
Beth        5.052394e+31
Carolina    1.694889e+28
dtype: float64

Andrea      98
Beth        73
Carolina    65
dtype: int64

In [12]:
s > 70

Andrea       True
Beth         True
Carolina    False
dtype: bool

In [13]:
# Series with NAs in it 
s = pd.Series([1, 2, np.nan, 4, np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [14]:
# .hasnans tells us if a series has nans in it 

s.hasnans

True

In [15]:
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [19]:
s = pd.Series([1, 2, -999, -999], index = ["A", "B", "C", "D"])
s.mask(s == -999)

A    1.0
B    2.0
C    NaN
D    NaN
dtype: float64

In [20]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
    }

# Create data frame 
df = pd.DataFrame(d)
df

   col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [22]:
# Change index using .index to change what is being indexed 
df.index = ['A', 'B' ,'C']
df

   col_name_1  col_name_2
A           0         3.1
B           1         3.2
C           2         3.3

In [23]:
df.columns = ["C1", "C2"]
df

   C1   C2
A   0  3.1
B   1  3.2
C   2  3.3